# Generated by Django 6.0.6 on 2026-06-15 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameDash_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_name',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='relase_date',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gener',
            new_name='title',
        ),
        migrations.CreateModel(
            name='PlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameDash_app.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameDash_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(related_name='game_player', through='gameDash_app.PlayerRole', to='gameDash_app.user'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
