# Generated by Django 6.0.6 on 2026-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameDash_app', '0002_rename_created_by_game_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='playerrole',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
