# Generated by Django 6.0.6 on 2026-06-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameDash_app', '0003_rename_birthday_user_birth_date_user_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player',
            new_name='players',
        ),
    ]
